# Generated by Django 2.2.6 on 2019-11-08 02:26

from django.db import migrations, models
import imagestorage.storage
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, storage=imagestorage.storage.ImageStorage(), upload_to='http://www.lixuejie.cn/', verbose_name='选择图片')),
                ('imagename', models.CharField(default='未命名图片', max_length=20, verbose_name='图片名')),
                ('upldtime', models.DateField(auto_now=True, verbose_name='上传时间')),
                ('chatime', models.DateField(auto_now=True, verbose_name='最后更改时间')),
            ],
            options={
                'verbose_name': '首页图片',
                'verbose_name_plural': '首页图片',
                'db_table': 'index_images',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, storage=imagestorage.storage.ImageStorage(), upload_to='http://www.lixuejie.cn/', verbose_name='选择图片')),
                ('imagename', models.CharField(default='未命名图片', max_length=20, verbose_name='图片名')),
                ('upldtime', models.DateField(auto_now=True, verbose_name='上传时间')),
                ('chatime', models.DateField(auto_now=True, verbose_name='最后更改时间')),
            ],
            options={
                'verbose_name': '作品展示',
                'verbose_name_plural': '作品展示',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='PythonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名文章', max_length=30, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(default="快捷键\n---------------------------\n撤销：Ctrl/Command + Z\n重做：Ctrl/Command + Y\n加粗：Ctrl/Command + B\n斜体：Ctrl/Command + I\n标题：Ctrl/Command + Shift + H\n无序列表：Ctrl/Command + Shift + U\n有序列表：Ctrl/Command + Shift + O\n检查列表：Ctrl/Command + Shift + C\n插入代码：Ctrl/Command + Shift + K\n插入链接：Ctrl/Command + Shift + L\n插入图片：Ctrl/Command + Shift + G\n查找：Command + F\n替换：Command + G\n\n标题\n---------------------------\n# 1级标题\n## 2级标题\n### 3级标题\n#### 四级标题 \n##### 五级标题  \n###### 六级标题\n\n文本样式\n---------------------------\n*强调文本* _强调文本_\n\n**加粗文本** __加粗文本__\n\n==标记文本==\n\n~~删除文本~~\n\n> 引用文本\n\nH~2~O is是液体。\n\n2^10^ 运算结果是 1024。\n\n列表\n---------------------------\n- 项目\n  * 项目\n    + 项目\n\n1. 项目1\n2. 项目2\n3. 项目3\n\n- [ ] 计划任务\n- [x] 完成任务\n\n链接\n---------------------------\n链接: [link](https://mp.csdn.net).\n\n图片: ![Alt](https://imgconvert.csdnimg.cn/aHR0cHM6Ly9hdmF0YXIuY3Nkbi5uZXQvNy83L0IvMV9yYWxmX2h4MTYzY29tLmpwZw)\n\n带尺寸的图片: ![Alt](https://imgconvert.csdnimg.cn/aHR0cHM6Ly9hdmF0YXIuY3Nkbi5uZXQvNy83L0IvMV9yYWxmX2h4MTYzY29tLmpwZw =30x30)\n\n居中的图片: ![Alt](https://imgconvert.csdnimg.cn/aHR0cHM6Ly9hdmF0YXIuY3Nkbi5uZXQvNy83L0IvMV9yYWxmX2h4MTYzY29tLmpwZw#pic_center)\n\n居中并且带尺寸的图片: ![Alt](https://imgconvert.csdnimg.cn/aHR0cHM6Ly9hdmF0YXIuY3Nkbi5uZXQvNy83L0IvMV9yYWxmX2h4MTYzY29tLmpwZw#pic_center =30x30)\n\n代码片\n---------------------------\n下面展示一些 `内联代码片`。\n\n```\n// A code block\nvar foo = 'bar';\n```\n\n```javascript\n// An highlighted block\nvar foo = 'bar';\n```\n\n表格\n---------------------------\n项目     | Value\n-------- | -----\n电脑  | $1600\n手机  | $12\n导管  | $1\n\n| Column 1 | Column 2      |\n|:--------:| -------------:|\n| centered 文本居中 | right-aligned 文本居右 |\n\n自定义列表\n---------------------------\nMarkdown\n:  Text-to-HTML conversion tool\n\nAuthors\n:  John\n:  Luke\n\n注脚\n---------------------------\n一个具有注脚的文本。[^1]\n\n[^1]: 注脚的解释\n\n注释\n---------------------------\nMarkdown将文本转换为 HTML。\n\n*[HTML]:   超文本标记语言\n\nLaTeX 数学公式\n---------------------------\n[参考文档](https://khan.github.io/KaTeX/)\n\nGamma公式展示 $\\Gamma(n) = (n-1)!\\quad\\forall\nn\\in\\mathbb N$ 是通过 Euler integral\n\n$$\n\\Gamma(z) = \\int_0^\\infty t^{z-1}e^{-t}dt\\,.\n$$\n\n插入甘特图\n---------------------------\n[参考文档](https://mermaidjs.github.io/#/gantt)\n\n```mermaid\ngantt\n        dateFormat  YYYY-MM-DD\n        title Adding GANTT diagram functionality to mermaid\n        section 现有任务\n        已完成               :done,    des1, 2014-01-06,2014-01-08\n        进行中               :active,  des2, 2014-01-09, 3d\n        计划中               :         des3, after des2, 5d\n```\n\n插入UML图\n---------------------------\n[参考文档](https://mermaidjs.github.io/#/sequenceDiagram)\n\n```mermaid\nsequenceDiagram\n张三 ->> 李四: 你好！李四, 最近怎么样?\n李四-->>王五: 你最近怎么样，王五？\n李四--x 张三: 我很好，谢谢!\n李四-x 王五: 我很好，谢谢!\nNote right of 王五: 李四想了很长时间, 文字太长了<br/>不适合放在一行.\n\n李四-->>张三: 打量着王五...\n张三->>王五: 很好... 王五, 你怎么样?\n```\n\n插入Mermaid流程图\n---------------------------\n[参考文档](https://mermaidjs.github.io/#/flowchart?id=graph)\n\n```mermaid\ngraph LR\nA[长方形] -- 链接 --> B((圆))\nA --> C(圆角长方形)\nB --> D{菱形}\nC --> D\n```\n\n插入Flowchart流程图\n---------------------------\n[参考文档](http://flowchart.js.org/)\n\n```mermaid\nflowchat\nst=>start: 开始\ne=>end: 结束\nop=>operation: 我的操作\ncond=>condition: 确认？\n\nst->op->cond\ncond(yes)->e\ncond(no)->op\n```\n", verbose_name='内容')),
                ('mktime', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('edittime', models.DateField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '已经发布的python文章',
                'verbose_name_plural': '已经发布的python文章',
                'db_table': 'Python_contents',
            },
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='名字')),
                ('phonenumber', models.CharField(max_length=11, verbose_name='手机号码')),
                ('time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_input',
            },
        ),
    ]
