# Generated by Django 2.2.7 on 2019-11-08 07:24

from django.db import migrations, models
import imagestorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191108_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, storage=imagestorage.storage.ImageStorage(), upload_to='images/', verbose_name='选择要上传的首页图片'),
        ),
        migrations.AlterField(
            model_name='index',
            name='imagename',
            field=models.CharField(default='未命名图片', max_length=20, verbose_name='首页图片名'),
        ),
        migrations.AlterField(
            model_name='index',
            name='self_introduction',
            field=models.CharField(default='毕业于郑州某大学，自学UI设计，云计算，linux系统管理和python以及一些主流的web框架。其中li    nux系统和python是强项，个人博客：\n', max_length=100, verbose_name='首页关于我'),
        ),
    ]
