# Generated by Django 2.2.7 on 2019-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191108_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='IndexMess',
        ),
    ]
