# Generated by Django 2.2.7 on 2019-11-08 07:55

from django.db import migrations, models
import imagestorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191108_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_int_now', models.CharField(default='毕业于郑州某大学，自学UI设计，云计算，linux系统管理和python以及一些主流的web框架。其中li    nux系统和python是强项，个人博客：\n', max_length=100, verbose_name='首页关于我:')),
            ],
            options={
                'db_table': 'QHTZ_index_about_me',
            },
        ),
        migrations.CreateModel(
            name='IndexImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, storage=imagestorage.storage.ImageStorage(), upload_to='images/', verbose_name='选择要上传的首页图片')),
                ('imagename', models.CharField(default='未命名图片', max_length=20, verbose_name='首页图片名')),
                ('upldtime', models.DateField(auto_now=True, verbose_name='上传时间')),
                ('chatime', models.DateField(auto_now=True, verbose_name='最后更改时间')),
            ],
            options={
                'verbose_name': '首页信息',
                'verbose_name_plural': '首页信息',
                'db_table': 'QHTZ_index_images',
            },
        ),
        migrations.DeleteModel(
            name='IndexMess',
        ),
        migrations.AlterModelOptions(
            name='pythonproduct',
            options={'verbose_name': '发布python文章', 'verbose_name_plural': '发布python文章'},
        ),
        migrations.AlterModelTable(
            name='productimages',
            table='QHTZ_product_images',
        ),
        migrations.AlterModelTable(
            name='pythonproduct',
            table='QHTZ_Python_contents',
        ),
        migrations.AlterModelTable(
            name='usermessages',
            table='QHTZ_user_input',
        ),
    ]
