# Generated by Django 2.2.7 on 2019-11-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191108_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexaboutme',
            options={'verbose_name': '首页关于我', 'verbose_name_plural': '首页关于我'},
        ),
        migrations.AlterModelOptions(
            name='indeximages',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'UI作品展示', 'verbose_name_plural': 'UI作品展示'},
        ),
        migrations.AlterModelOptions(
            name='pythonproduct',
            options={'verbose_name': 'python文章', 'verbose_name_plural': 'python文章'},
        ),
        migrations.AddField(
            model_name='indeximages',
            name='show',
            field=models.BooleanField(default='True', verbose_name='是否在首页展示'),
        ),
    ]
