# Generated by Django 2.2.7 on 2019-11-12 03:00

from django.db import migrations, models
import imagestorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191112_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='show',
            field=models.BooleanField(default='True', verbose_name='是否在首页展示'),
        ),
        migrations.AlterField(
            model_name='indeximages',
            name='image',
            field=models.ImageField(blank=True, storage=imagestorage.storage.ImageStorage(), upload_to='images/', verbose_name='选择要上传的图片'),
        ),
    ]
