# Generated by Django 2.2.7 on 2019-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20191112_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeximages',
            name='show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
