# Generated by Django 2.2.7 on 2019-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_checkjianli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkjianli',
            name='ex_time',
            field=models.DateTimeField(auto_now=True, verbose_name='a访问时间'),
        ),
    ]
