# Generated by Django 2.2.7 on 2019-11-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20191119_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexaboutme',
            name='show',
            field=models.BooleanField(default=False, verbose_name='是否首页显示'),
        ),
        migrations.AlterField(
            model_name='checkjianli',
            name='ex_time',
            field=models.DateTimeField(auto_now=True, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='indexaboutme',
            name='self_int_now',
            field=models.CharField(default='毕业于郑州某大学，自学UI设计，云计算，linux系统管理和python以及一些主流的web框架。其中linux系统和python是强项，个人博客：\n', max_length=100, verbose_name='首页关于我:'),
        ),
    ]
