# Generated by Django 2.2.7 on 2019-11-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20191119_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkjianli',
            name='ex_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='访问时间'),
        ),
    ]
