# Generated by Django 2.2.7 on 2019-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_checkjianli_ipaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkjianli',
            name='tips',
            field=models.CharField(default='注意：以下所有项均不可更改', max_length=15),
        ),
    ]
