# Generated by Django 2.2.7 on 2019-11-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_checkjianli_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkjianli',
            name='area',
            field=models.CharField(default='中国,北京(默认地址)', max_length=30, verbose_name='访问者所在地区'),
        ),
        migrations.AlterField(
            model_name='checkjianli',
            name='tips',
            field=models.CharField(default='注意：以上所有项均不可更改', max_length=15),
        ),
    ]
