# Generated by Django 2.2.7 on 2019-11-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20191126_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkjianli',
            name='tips',
            field=models.CharField(default='注意：此项所有内容仅供查看,不可更改', max_length=35),
        ),
    ]
