# Generated by Django 2.2.7 on 2019-12-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20191127_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.DateTimeField(auto_now=True, verbose_name='访问时间')),
                ('traffic_ip', models.ForeignKey(on_delete='CASCADE', to='index.CheckJianli', verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '网站访问记录',
                'verbose_name_plural': '网站访问记录',
                'db_table': 'QHTZ_traffic',
            },
        ),
    ]
