# Generated by Django 2.2.7 on 2019-12-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='view_times',
            field=models.IntegerField(default=0, verbose_name='访问次数'),
        ),
    ]
