# Generated by Django 2.2.7 on 2019-12-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_traffic_view_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='traffic_ip',
            field=models.CharField(max_length=15, verbose_name='访问次数'),
        ),
    ]
