# Generated by Django 2.2.7 on 2020-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20191230_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonproduct',
            name='title',
            field=models.CharField(default='未命名文章', max_length=130, verbose_name='标题'),
        ),
    ]
